### ISSUE TITLE
Setup of Neural Search Plugin

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/neural-search#1]
### Description
The task involves the setting up of the Neural Search plugin for development.

### Tasks:

- [x] Setup the code for the repo
- [x] Update the Description of the repo
- [ ] Setup the Developer guide
- [x] Add the merge policy like: Don't merge the code without approval, 2 person approval.
- [x] Setup the labels.
- [x] Setup the 2.x branches
- [x] Add update version task 
- [x] Show Jacoco reports when Pull request is created
- [x] Run CI checks periodically
- [x] Add the badges to Readme.

**Comment by martin-gaievski** [comment]
I'm pretty sure that's done, closing
