### ISSUE TITLE
[META] Score Combination and Normalization for Semantics Search.  Score Normalization for k-NN and BM25

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/neural-search#123]
### Is your feature request related to a problem?
BM25 works well in exact match use cases and k-NN score works well in understanding context and getting relevant documents. It is important to get benefits from both of these relevancy mechanisms and one could achieve by combining these scores. One caveat is scores are on different scales and hence some kind of normalization is required.  

### Older Issues and Discussions:
1. https://github.com/opensearch-project/k-NN/issues/717
2. https://github.com/opensearch-project/OpenSearch/issues/4557
3. Science Benchmarks: https://opensearch.org/blog/semantic-science-benchmarks/

### Tasks
High Level Tasks:
- [X] Create RFC for the Feature Request. https://github.com/opensearch-project/neural-search/issues/126
- [X] Build POC for the Feature.
- [X] Low Level Design of various components.
    - [X] API Design https://github.com/opensearch-project/neural-search/issues/244
    - [X] Search Phase Results Processor: https://github.com/opensearch-project/neural-search/issues/152
    - [X] Different Normalization and Score combination Methods: https://github.com/opensearch-project/neural-search/issues/228
    - [X] New Doc Collector For Query Clause: https://github.com/opensearch-project/neural-search/issues/228
    - [X] LLD for New Query Phase Searcher: https://github.com/opensearch-project/neural-search/issues/228
- [x] Validate Accuracy of the solution.
- [ ] Perf Testing and release tasks.
- [x] Documentation issue for Normalization and Score combination feature: https://github.com/opensearch-project/documentation-website/issues/4351

### Community Requests
1. https://forum.opensearch.org/t/normalisation-in-hybrid-search/12996

**Comment by navneet1v** [comment]
RFC created with HLD: https://github.com/opensearch-project/neural-search/issues/126

**Comment by martin-gaievski** [comment]
RFC with design for Query: https://github.com/opensearch-project/neural-search/issues/174
Created new Feature issue for Query: https://github.com/opensearch-project/neural-search/issues/175

**Comment by DarshitChanpura** [comment]
@vamshin Should this issue be moved to 2.11?

**Comment by vamshin** [comment]
@DarshitChanpura we are releasing this feature for 2.10

**Comment by navneet1v** [comment]
@martin-gaievski can we add the perf results on this issue and then resolve this github issue.

**Comment by martin-gaievski** [comment]
Summary for performance benchmark

dataset | p50 bool (baseline) | p50 hybrid | p50 difference, ms | p90 bool (baseline) | p90 hybrid | p90 difference, ms | p99 bool (baseline) | p99 hybrid | p99 difference, ms
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
nfcorpus | 35.1 | 37 | 1.9 | 53 | 54 | 1 | 60.8 | 62.3 | 1.5
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
trec-covid | 58.1 | 61.6 | 3.5 | 66.4 | 70 | 3.6 | 70.5 | 74.6 | 4.1
scidocs | 54.9 | 57 | 2.1 | 66.4 | 68.6 | 2.2 | 81.3 | 83.2 | 1.9
quora | 61 | 69 | 8 | 69 | 78 | 9 | 73.4 | 84 | 10.6
amazon esci | 49 | 50 | 1 | 58 | 59.4 | 1.4 | 67 | 70 | 3
dbpedia | 100.8 | 107.7 | 6.9 | 117 | 130.9 | 13.9 | 129.8 | 150.2 | 20.4
fiqa | 53.9 | 56.9 | 3 | 61.9 | 65 | 3.1 | 64 | 67.7 | 3.7
**% change vs. Boolean** | | |  6.40% | | | 6.96% | | | 8.27%

We took a bool query with `neural` and `match` sub-queries as a baseline.

For the cluster configuration, we used 3 data nodes of type “r5.8xlarge” and 1 leader node of type “c4.2xlarge”. All scripts that we use for benchmarks can be found in [this repository](https://github.com/martin-gaievski/info-retrieval-test/tree/score-normalization-combination-testing).
