### ISSUE TITLE
[FEATURE] : Search Phase Results Processor in Search Pipeline

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/neural-search#139]
## Description
For Normalization and Score Combination feature, we need a way to do the Normalization of scores received for different sub-queries from different shards at Coordinator node, before we can start combing the scores. This needs to be done after the Query phase is completed and before Fetch Phase is started in a _search api call.

## Solution
The solution I am proposing is to extend the [Search Pipeline](https://github.com/opensearch-project/search-processor/issues/80) Processor to create a new Processor Interface called as Search Phase Processors that can run between Phases of Search(There are many phases Search like DFS, Query, Fetch, Expand etc). 

As first use-case we will create a new SearchPhase Processor that will run between Query and Fetch phase, which do the Normalization of Scores and combine the Scores after normalization.

### Alternatives
The alternative approaches are defined in the Section: Obtaining Relevant Information for Normalization and score Combination in https://github.com/opensearch-project/neural-search/issues/126

## Task

- [x] Create RFC for New Processor Interface : https://github.com/opensearch-project/neural-search/issues/152
- [x] Implementation of Search Phase Processor Interface
- [x] Implementation of Normalization Processor
- [x] Testing

## Reference Links
1. https://github.com/opensearch-project/neural-search/issues/126
2. https://github.com/opensearch-project/search-processor/issues/80

**Comment by navneet1v** [comment]
PR: https://github.com/opensearch-project/OpenSearch/pull/7283

**Comment by navneet1v** [comment]
Resolving this issue as this feature is launched in 2.10 version of OpenSearch
