### ISSUE TITLE
Integrate ML Commons lib and K-NN Plugin

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/neural-search#4]
### Description
As a part of Ingestion and Search we are dependent on ML Commons Lib to create the embeddings for query string and user document and K-NN plugin for doing K-NN search. This task tracks the integration of ML commons lib in Neural-Search Plugin.

K-NN Plugin: https://github.com/opensearch-project/k-NN
ML Commons: https://github.com/opensearch-project/ml-commons

## Tasks

- [x] Integrate ML Commons Lib in Repo
- [x] Unit test for the Interface
- [x] Integrate K-NN plugin
- [x] Unit test for the interface
